Test feature
vikitaotiz/todo_list_review pull request #2
Opened 2021-08-25 16:02 UTC by vikitaotiz

The project tests the us of unit test in javascript using jest.
We have added test for add method
We have added test for remove method

2021-08-25 16:39 UTC, mikenath223 requested changes
Hello Team 👋,

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._


Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-25 16:40 UTC, mikenath223 commented on src/util.test.js
> +/* eslint-disable */
- [ ] Kindly avoid disabling eslint rules. Rather fix the issue in the code.

2021-08-25 16:41 UTC, mikenath223 commented on src/util.test.js
> +require('jest-localstorage-mock');
- [ ] Please use the `es6` `import` syntax instead.

2021-08-25 18:49 UTC, AshakaE requested changes
### Hi @vikitaotiz 🙋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 # Required Changes ♻️ 🚧 
Please work on the changes previously requested 🙏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-25 19:06 UTC, blakbox23 commented
Hello @AshakaE  We've made the required changes in the tests. What exactly are we missing? These are the changes we've made in accordance to the last review.
 These changes include

- [x]  Avoid disabling eslint rules. 
- [x]  Using the es6 import syntax.

2021-08-26 10:11 UTC, Davidosky007 commented
## Hi @vikitaotiz @blakbox23 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 
![job-welldone-gif](https://user-images.githubusercontent.com/52497246/130944876-688997e6-5d48-481a-9897-33952e20d423.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-26 11:03 UTC, merged